### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by krymancer** [Krymancer/classic-mario#1]
- [x] Make briks collison animation 
- [ ] Make lucky block interaction and collison animation
- [ ] Make death animation
- [ ] Make death behaviour
- [x] Rewrite levels/1-1.json to match as the original game 1-1 level
- [x]  Adding more background environment (leaves and more clouds)
- [ ]  Document the engine as well the game
